{{- if .Values.locustfile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
  namespace: {{ .Values.namespace }}
  labels:
    app: locust
data:
  locustfile.py: |
{{ .Files.Get "behaviour/locustfile.py" | indent 4 }}
{{- end }}
