apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.master.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: locust
    component: master
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: locust
      component: master
  template:
    metadata:
      labels:
        app: locust
        component: master
    spec:
      containers:
      - name: locust-master
        image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
        imagePullPolicy: {{ .Values.master.image.pullPolicy }}
        env:
        - name: LOCUST_HOST
          value: "{{ .Values.master.config.targetHost }}"
        args:
        - "--master"
        - "--web-port={{ .Values.master.service.webPort }}"
        - "--host=$(LOCUST_HOST)"
        - "--locustfile={{ .Values.master.config.locustFile }}"
        - "--class-picker"
        ports:
        - containerPort: {{ .Values.master.service.webPort }}
          name: web
          protocol: TCP
        - containerPort: {{ .Values.master.service.masterPort }}
          name: master
          protocol: TCP
        - containerPort: {{ .Values.master.service.workerPort }}
          name: worker
          protocol: TCP
        resources:
          {{- toYaml .Values.master.resources | nindent 10 }}
        volumeMounts:
        - name: locustfile
          mountPath: /mnt/locust
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.master.service.webPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.master.service.webPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: locustfile
        configMap:
          name: locust-config
