app:
  name: met-web
  licenseplate: e903c2

deployment:
  minReplicas: 2
  maxReplicas: 3

image:
  tag: latest
  namespace: e903c2-tools
  repository: "image-registry.openshift-image-registry.svc:5000/e903c2-tools"

tenants:
  default: "GDX"

vault:
  namespace: "platform-services"
  authPath: "auth/k8s-gold"
