app:
  name: analytics-api
  licenseplate: e903c2
  ratelimits:
    enabled: true
    http: 40
    tcp: 45

hpa:
  minReplicas: 2
  maxReplicas: 3
  cpuUtilizationPercentage: 80

image:
  tag: latest
  namespace: e903c2-tools
  repository: "image-registry.openshift-image-registry.svc:5000/e903c2-tools"

vault:
  namespace: "platform-services"
  authPath: "auth/k8s-gold"
