name: ZAP Scanner
on:
  workflow_dispatch:

jobs:
  zap_scan_web:
    runs-on: ubuntu-latest
    name: Scan the met application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'WEB ZAP Scan Report'
          target: 'https://met-web-dev.apps.gold.devops.gov.bc.ca/'

  zap_scan_notify:
    runs-on: ubuntu-latest
    name: Scan the notify application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Notify ZAP Scan Report'
          target: 'https://met-notify-api-dev.apps.gold.devops.gov.bc.ca/'

  zap_scan_analytics:
    runs-on: ubuntu-latest
    name: Scan the analytics application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Analytics ZAP Scan Report'
          target: 'https://met-analytics-api-dev.apps.gold.devops.gov.bc.ca/'
